# Generated by Django 6.0.6 on 2026-06-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_pais_alter_estudiante_id_alter_numerotelefonico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='capital',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='numero_habitantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pais',
            name='numero_provincias',
            field=models.IntegerField(default=0),
        ),
    ]
